/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          colors: {
              "secondary-fixed-dim": "#ffb693",
              "on-secondary": "#ffffff",
              "on-primary-fixed-variant": "#39475f",
              "tertiary-container": "#111c2c",
              "on-surface": "#181c1e",
              "tertiary-fixed": "#d8e3fa",
              "error-container": "#ffdad6",
              "primary-container": "#0d1c32",
              "background": "#f7fafc",
              "surface-container-high": "#e5e9eb",
              "outline-variant": "#c5c6cd",
              "tertiary": "#000000",
              "surface-bright": "#f7fafc",
              "secondary": "#a04100",
              "on-error": "#ffffff",
              "surface-container-lowest": "#ffffff",
              "outline": "#75777e",
              "surface-container-highest": "#e0e3e5",
              "primary-fixed": "#d6e3ff",
              "on-tertiary": "#ffffff",
              "surface-tint": "#515f78",
              "secondary-container": "#fe6b00",
              "surface-container-low": "#f1f4f6",
              "surface": "#f7fafc",
              "surface-container": "#ebeef0",
              "primary-fixed-dim": "#b9c7e4",
              "tertiary-fixed-dim": "#bcc7dd",
              "on-secondary-fixed-variant": "#7a3000",
              "on-error-container": "#93000a",
              "inverse-primary": "#b9c7e4",
              "on-primary-container": "#76849f",
              "surface-variant": "#e0e3e5",
              "on-secondary-container": "#572000",
              "on-tertiary-container": "#798499",
              "on-primary-fixed": "#0d1c32",
              "on-background": "#181c1e",
              "on-primary": "#ffffff",
              "inverse-surface": "#2d3133",
              "on-tertiary-fixed": "#111c2c",
              "on-surface-variant": "#44474d",
              "secondary-fixed": "#ffdbcc",
              "surface-dim": "#d7dadc",
              "primary": "#000000",
              "on-secondary-fixed": "#351000",
              "on-tertiary-fixed-variant": "#3c475a",
              "inverse-on-surface": "#eef1f3",
              "error": "#ba1a1a"
          },
          borderRadius: {
              DEFAULT: "0.375rem",
              sm: "0.25rem",
              lg: "0.625rem",
              xl: "0.875rem",
              "2xl": "1.25rem",
              "3xl": "1.75rem",
              full: "9999px"
          },
          spacing: {
              gutter: "24px",
              "container-max": "1280px",
              "margin-mobile": "16px",
              unit: "4px",
              "section-padding": "80px",
              "stack-lg": "32px",
              "stack-md": "16px",
              "stack-sm": "8px"
          },
          fontFamily: {
              "display-lg": ["Manrope", "sans-serif"],
              "body-md": ["Inter", "sans-serif"],
              "headline-sm": ["Manrope", "sans-serif"],
              "headline-md": ["Manrope", "sans-serif"],
              "body-lg": ["Inter", "sans-serif"],
              "label-caps": ["Inter", "sans-serif"],
              "mono-data": ["Inter", "sans-serif"],
              "display-lg-mobile": ["Manrope", "sans-serif"]
          },
          fontSize: {
              "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
              "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
              "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
              "headline-md": ["32px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "700" }],
              "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
              "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "600" }],
              "mono-data": ["14px", { lineHeight: "1.0", letterSpacing: "0.02em", fontWeight: "500" }],
              "display-lg-mobile": ["36px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }]
          }
      }
  },
  plugins: [],
}
